plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mmggh.vollaflashfix'
    compileSdk 34

    defaultConfig {
        applicationId "com.mmggh.vollaflashfix"
        minSdk 33
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
